# Generated by Django 5.1.1 on 2025-11-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_owner_cat_owner'),
    ]

    operations = [
    ]
